baseURL = 'https://www.makinoguitars.com'
languageCode = 'en-us'
title = 'Makino Guitars'
theme = 'hugo-bootstrap'
navbarBgColorClass = 'secondary'


[[menu.main]]
    name = "Guitars"
    pre = ""
    weight = -20
    identifier = "guitars"
    url = "/guitars/"

[[menu.main]]
    name = "Order"
    pre = ""
    weight = -15
    identifier = "Order"
    url = "/order/"

[[menu.main]]
    name = "About"
    pre = ""
    weight = -10
    identifier = "About"
    url = "/about/"

[[menu.main]]
    name = ""
    pre = "<i class='fab fa-instagram'></i>"
    weight = -5
    identifier = "instagram"
    url = "https://www.instagram.com/takmakino"

[[menu.main]]
    name = ""
    pre = "<i class='fas fa-envelope-square'></i>"
    weight = 10
    identifier = "contact"
    url = "mailto:tak@makinoguitars.com"

    